package io.slifer.automation.reporter;

import org.testng.ITestResult;

import java.util.HashMap;

/**
 * Tracks and links the TestNG results for each test to the UUID generated by the MDC in the Logback logs.
 *
 * @author Tim Slifer
 */
public class ResultsMap extends HashMap<String, ITestResult> {
    
    private String suiteName;
    
    public String getSuiteName() {
        return suiteName;
    }
    
    public void setSuiteName(String suiteName) {
        this.suiteName = suiteName;
    }
}
